[build]
  base = "frontend"
  publish = ".next"
  command = "npm ci && NEXT_LINT_IGNORE_BUILD_ERROR=true npm run build"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_LINT_IGNORE_BUILD_ERROR = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"
