[build]
  base = "frontend"
  publish = ".next"
  command = "node build-ignore-errors.js"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_LINT_IGNORE_BUILD_ERROR = "true"
  CI = "false"
  TYPESCRIPT_SKIP_ERRORS = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"
